-- Shrine Ops - Minimal Setup (only missing tables/policies)

-- Only create each table if it doesn't exist
CREATE TABLE IF NOT EXISTS profiles ();
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS full_name TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'operations';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS events ();
ALTER TABLE events ADD COLUMN IF NOT EXISTS id BIGSERIAL PRIMARY KEY;
ALTER TABLE events ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS start_time TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN IF NOT EXISTS end_time TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'standard';
ALTER TABLE events ADD COLUMN IF NOT EXISTS dcs_link TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS required_ops INT DEFAULT 0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS required_security INT DEFAULT 0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS required_greeter INT DEFAULT 0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS director_mandatory BOOLEAN DEFAULT false;
ALTER TABLE events ADD COLUMN IF NOT EXISTS google_event_id TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE events ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS shifts ();
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS id UUID PRIMARY KEY DEFAULT gen_random_uuid();
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS event_id BIGINT;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS clock_in TIMESTAMPTZ;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS clock_out TIMESTAMPTZ;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS staff_assignments ();
ALTER TABLE staff_assignments ADD COLUMN IF NOT EXISTS id UUID PRIMARY KEY DEFAULT gen_random_uuid();
ALTER TABLE staff_assignments ADD COLUMN IF NOT EXISTS event_id BIGINT;
ALTER TABLE staff_assignments ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE staff_assignments ADD COLUMN IF NOT EXISTS role_assigned TEXT;
ALTER TABLE staff_assignments ADD COLUMN IF NOT EXISTS shift_start TIMESTAMPTZ;
ALTER TABLE staff_assignments ADD COLUMN IF NOT EXISTS shift_end TIMESTAMPTZ;
ALTER TABLE staff_assignments ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS messages ();
ALTER TABLE messages ADD COLUMN IF NOT EXISTS id UUID PRIMARY KEY DEFAULT gen_random_uuid();
ALTER TABLE messages ADD COLUMN IF NOT EXISTS sender_id UUID;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS recipient_id UUID;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_urls JSONB DEFAULT '[]';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS read_at TIMESTAMPTZ;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS notifications ();
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS id UUID PRIMARY KEY DEFAULT gen_random_uuid();
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS body TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'info';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS read_at TIMESTAMPTZ;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS reference_id TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE TABLE IF NOT EXISTS maintenance_tickets ();
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS id UUID PRIMARY KEY DEFAULT gen_random_uuid();
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS user_id UUID;
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS event_id BIGINT;
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'low';
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'open';
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS media_urls JSONB DEFAULT '[]';
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS assigned_to UUID;
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE maintenance_tickets ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS visitor_volume ();
ALTER TABLE visitor_volume ADD COLUMN IF NOT EXISTS id UUID PRIMARY KEY DEFAULT gen_random_uuid();
ALTER TABLE visitor_volume ADD COLUMN IF NOT EXISTS event_id BIGINT;
ALTER TABLE visitor_volume ADD COLUMN IF NOT EXISTS count INT;
ALTER TABLE visitor_volume ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE visitor_volume ADD COLUMN IF NOT EXISTS recorded_by UUID;

-- Trigger (replace if exists)
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'role', 'operations'))
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION handle_new_user();

SELECT 'Minimal Setup Complete! No data lost.' as status;
