/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        display: ['var(--font-manrope)', 'system-ui', 'sans-serif'],
        headline: ['var(--font-manrope)', 'system-ui', 'sans-serif'],
        body: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        label: ['var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      colors: {
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'secondary-container': 'var(--secondary-container)',
        'inverse-primary': 'var(--inverse-primary)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        error: 'var(--error)',
        'on-background': 'var(--on-background)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'primary-container': 'var(--primary-container)',
        surface: 'var(--surface)',
        'on-primary-container': 'var(--on-primary-container)',
        'surface-bright': 'var(--surface-bright)',
        'on-surface': 'var(--on-surface)',
        tertiary: 'var(--tertiary)',
        'on-secondary': 'var(--on-secondary)',
        background: 'var(--background)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'error-container': 'var(--error-container)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'surface-container': 'var(--surface-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        primary: 'var(--primary)',
        'surface-container-low': 'var(--surface-container-low)',
        'tertiary-container': 'var(--tertiary-container)',
        'primary-fixed': 'var(--primary-fixed)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        outline: 'var(--outline)',
        'surface-variant': 'var(--surface-variant)',
        'outline-variant': 'var(--outline-variant)',
        secondary: 'var(--secondary)',
        'inverse-surface': 'var(--inverse-surface)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'surface-dim': 'var(--surface-dim)',
        'on-error': 'var(--on-error)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'on-primary': 'var(--on-primary)',
        'on-error-container': 'var(--on-error-container)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-tint': 'var(--surface-tint)',
        'on-tertiary': 'var(--on-tertiary)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'secondary-fixed': 'var(--secondary-fixed)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      spacing: {
        'section': '3rem',
      },
    },
  },
  plugins: [],
}
